### ISSUE TITLE
TypeError: Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by djohannes** [bunqCommunity/bunqDesktop#486] opened 2019-02-27 01:37 UTC
### Bug report

Hi,

since the new update my bunqDesktop is basically not working anymore, also after a re-installation. The first time it shows my accounts, but it doesn't load the payments.. then I get the:
"TypeError: Cannot read property 'status' of undefined" - error.

**Comment by djohannes** [comment] 2019-02-27 09:06
.. If you need more information about this I would be happy to provide them :)

**Comment by Crecket** [comment] 2019-02-27 09:07
This is likely caused by a breaking API change on bunq's end. One of the connect models got a name change so it should be an easy fix :+1:

**Comment by Mauricevb** [comment] 2019-02-27 09:45
Do you think it's possible to release a hotfix with these changes?

**Comment by Crecket** [comment] 2019-02-27 10:21
Later today probably

**Comment by Crecket** [comment] 2019-02-27 19:17
Fixed by bunq 👍  I'll release a new version with some of the new changes later aswell

**Closed by Crecket** 2019-02-27 19:17 UTC
Labels: Type: Bug
