### ISSUE TITLE
Auto correct IBAN number / accept characters

### ISSUE THREAD

**Issue by coinnodenl** [bunqCommunity/bunqDesktop#382] opened 2018-10-18 07:26 UTC
Got two things that annoy;

- If you dont use capitals in the iban number it will throw an error when you want to pay. Could be easely solved by auto capital the letters.

- You cant use characters in payment description not even if its part of a language like finish.

**Comment by Crecket** [comment] 2018-10-18 17:39
Do you mean with the second point that special characters aren't allowed?

**Comment by Crecket** [comment] 2018-10-18 17:42
I fixed issue 1 and improved the iban name field so that one also autocompletes and fills in the IBAN number when possible 👍

**Comment by coinnodenl** [comment] 2018-10-18 17:49
@crecket, 

Yes

**Comment by Crecket** [comment] 2018-10-18 17:58
Could you send some example text that doesn't work? I can't reproduce it right now

**Comment by coinnodenl** [comment] 2018-10-18 18:14
Sorry, its characters as #_ that dont work

**Comment by Crecket** [comment] 2018-10-18 18:35
I tried those and they seem to work just fine, what is the exact bug? That the description field is red/in the error state?

**Comment by Crecket** [comment] 2018-10-22 18:41
Nothing in bunqDesktop prevents you from using uncommon characters so if you mean you get an API error screen than there is nothing I can do about it. Closing this for now unless I know how to reproduce a fix-able error for this

**Closed by Crecket** 2018-10-22 18:41 UTC
Labels: Type: Bug
