### ISSUE TITLE
Emojis are not showing up on Linux client 

### ISSUE THREAD

**Issue by Yornik** [BunqCommunity/BunqDesktop#166] opened 2018-04-06 23:14 UTC
Hello i installed the correct fonts on linux 
But just got a missing char block.

It works fine in windows.

![3rfyyga](https://user-images.githubusercontent.com/1230966/38447917-e40c8240-3a00-11e8-8ad2-acee6c5b16d8.png)

Using version 
0.8.1 on windows and linux

**Comment by Yornik** [comment] 2018-04-07 00:01
Arch linux It is showing up using the src build from aur and when I use the appimage.

seems to be fixed in ubuntu 17.10 , so maybe it is not a bug but just a missing dependency. 

![image](https://user-images.githubusercontent.com/1230966/38448758-4b8d43ae-3a07-11e8-84d1-875462902e8b.png)

**Comment by Crecket** [comment] 2018-04-07 07:45
I checked and it seems Electron is dependent on the system fonts, so I'm not entirely sure if this is something I can easily fix with the current system

**Comment by Crecket** [comment] 2018-04-09 17:56
Since I don't maintain the Arch linux builds and I can't reproduce the issue myself I'm going to close this. 
Feel free to open a PR if you know how to fix this for your specific build/version

**Closed by Crecket** 2018-04-09 17:56 UTC
Labels: Type: Bug
