### ISSUE TITLE
Cards do not load

### ISSUE THREAD

**Issue by gctheol** [bunqCommunity/bunqDesktop#466] opened 2019-01-02 11:59 UTC
When I try to open the cards screen I get an error message "We failed to load the cards overview".
I have 2 active cards and 1 canceled card in my account.

I'm using latest bunqDesktop (0.9.5) on a mac mini (10.14.2).

Screenshot from bunq desktop:
![bildschirmfoto 2019-01-02 um 12 51 41](https://user-images.githubusercontent.com/10502633/50591007-aac92f80-0e8d-11e9-8782-f4503f78f47a.png)

Screenshot from official bunq app cards overview (german):
![img_1835](https://user-images.githubusercontent.com/10502633/50591080-fc71ba00-0e8d-11e9-873c-398dc436d3eb.jpeg)

**Comment by Crecket** [comment] 2019-02-27 19:15
I can't reproduce this myself and after checking the code this was likely related to the API itself so I'm closing this for now.

**Comment by Crecket** [comment] 2019-02-28 15:15
Caused by the broken logger `Logger.js?fbd5:11 Invalid attempt to spread non-iterable instance`

**Closed** 2019-03-02 11:21 UTC
Labels: Type: Bug
